import { Guest, Partner, BusinessMetric, ChurnProfile } from './types';

export const guests: Guest[] = [
  {
    id: 'G001',
    name: 'TechCorp International',
    type_client: 'Entreprise',
    session_duration: 12,
    room_observation_time: { 'Pitch Room': 6, 'Showcase Room': 3, 'Training Center': 2 },
    room_click_rate: { 'Pitch Room': 3, 'Showcase Room': 1, 'Training Center': 1 },
    rooms_viewed: ['Pitch Room', 'Showcase Room', 'Training Center'],
    interaction_count: 25,
    most_viewed_room: 'Pitch Room',
    voice_interaction_time: 2,
    customization_time: 1,
    idle_time: 0,
    status: 'Converti',
    created_at: '2025-01-15',
  },
  {
    id: 'G002',
    name: 'Institut National Formation',
    type_client: 'Institution',
    session_duration: 3,
    room_observation_time: { 'Lobby': 3 },
    room_click_rate: {},
    rooms_viewed: ['Lobby'],
    interaction_count: 5,
    most_viewed_room: 'Lobby',
    voice_interaction_time: 0,
    customization_time: 0,
    idle_time: 2,
    status: 'Lobby',
    created_at: '2025-02-02',
  },
  {
    id: 'G003',
    name: 'InnovateTech Solutions',
    type_client: 'Entreprise',
    session_duration: 20,
    room_observation_time: { 'Training Center': 10, 'Showcase Room': 5, 'Opportunity Room': 3 },
    room_click_rate: { 'Training Center': 5, 'Showcase Room': 2, 'Opportunity Room': 1 },
    rooms_viewed: ['Training Center', 'Showcase Room', 'Opportunity Room'],
    interaction_count: 40,
    most_viewed_room: 'Training Center',
    voice_interaction_time: 5,
    customization_time: 3,
    idle_time: 0,
    status: 'Converti',
    created_at: '2025-01-28',
  },
  {
    id: 'G004',
    name: 'EduPrime Academy',
    type_client: 'Institution',
    session_duration: 8,
    room_observation_time: { 'Training Center': 4, 'Showcase Room': 3 },
    room_click_rate: { 'Training Center': 2, 'Showcase Room': 1 },
    rooms_viewed: ['Training Center', 'Showcase Room'],
    interaction_count: 15,
    most_viewed_room: 'Training Center',
    voice_interaction_time: 1,
    customization_time: 0.5,
    idle_time: 1,
    status: 'Offre envoyée',
    created_at: '2025-02-10',
  },
  {
    id: 'G005',
    name: 'StartupHub Ventures',
    type_client: 'Entreprise',
    session_duration: 15,
    room_observation_time: { 'Pitch Room': 8, 'Opportunity Room': 5 },
    room_click_rate: { 'Pitch Room': 4, 'Opportunity Room': 2 },
    rooms_viewed: ['Pitch Room', 'Opportunity Room'],
    interaction_count: 30,
    most_viewed_room: 'Pitch Room',
    voice_interaction_time: 3,
    customization_time: 2,
    idle_time: 0,
    status: 'KPIs collectés',
    created_at: '2025-03-01',
  },
];

export const partners: Partner[] = [
  {
    id: 'P001',
    name: 'Digital Dynamics Corp',
    type_client: 'Entreprise',
    level: 'Partenaire Fiable',
    subscribed_rooms: ['Training Center', 'Showcase Room', 'Opportunity Room', 'Pitch Room'],
    engagement_score: 85,
    kpis: [
      { room: 'Showcase Room', sessions: 10, projets_presentes: 5, visites: 120, interactions: 45, avg_rating: 4.5 },
      { room: 'Training Center', sessions: 8, participants: 25, avg_time: 45, certifications: 12, avg_rating: 4.2 },
      { room: 'Opportunity Room', sessions: 6, invitations: 15, entretiens: 8, recrutements: 3, avg_rating: 4.0 },
      { room: 'Pitch Room', sessions: 4, pitchs: 3, participants: 40, entreprises: 10, discussion_duration: 120, avg_rating: 4.6 },
    ],
    upsell_done: true,
    created_at: '2024-11-01',
  },
  {
    id: 'P002',
    name: 'FormaPro Institute',
    type_client: 'Institution',
    level: 'Partenaire',
    subscribed_rooms: ['Training Center'],
    engagement_score: 70,
    kpis: [
      { room: 'Training Center', sessions: 5, participants: 15, avg_time: 30, certifications: 5, avg_rating: 3.8 },
    ],
    upsell_done: false,
    created_at: '2025-01-05',
  },
  {
    id: 'P003',
    name: 'VenturePitch Global',
    type_client: 'Entreprise',
    level: 'Partenaire Fiable',
    subscribed_rooms: ['Training Center', 'Showcase Room', 'Opportunity Room', 'Pitch Room'],
    engagement_score: 92,
    kpis: [
      { room: 'Pitch Room', sessions: 12, pitchs: 8, participants: 60, entreprises: 20, discussion_duration: 200, avg_rating: 4.8 },
      { room: 'Showcase Room', sessions: 7, projets_presentes: 4, visites: 90, interactions: 35, avg_rating: 4.3 },
      { room: 'Training Center', sessions: 5, participants: 18, avg_time: 40, certifications: 8, avg_rating: 4.1 },
      { room: 'Opportunity Room', sessions: 9, invitations: 20, entretiens: 12, recrutements: 5, avg_rating: 4.5 },
    ],
    upsell_done: true,
    created_at: '2024-10-15',
  },
  {
    id: 'P004',
    name: 'SkillBridge Academy',
    type_client: 'Institution',
    level: 'Partenaire',
    subscribed_rooms: ['Training Center', 'Showcase Room'],
    engagement_score: 65,
    kpis: [
      { room: 'Training Center', sessions: 7, participants: 20, avg_time: 35, certifications: 9, avg_rating: 4.0 },
      { room: 'Showcase Room', sessions: 3, projets_presentes: 2, visites: 40, interactions: 12, avg_rating: 3.5 },
    ],
    upsell_done: false,
    created_at: '2025-01-20',
  },
];

export const businessMetrics: BusinessMetric[] = [
  { month: 'Jan', mrr: 5000, cac: 200, ltv: 1200, conversion_rate: 12, churn_rate: 8 },
  { month: 'Fév', mrr: 6500, cac: 180, ltv: 1400, conversion_rate: 15, churn_rate: 6 },
  { month: 'Mar', mrr: 7200, cac: 220, ltv: 1500, conversion_rate: 18, churn_rate: 5 },
  { month: 'Avr', mrr: 8100, cac: 195, ltv: 1600, conversion_rate: 20, churn_rate: 4.5 },
  { month: 'Mai', mrr: 9000, cac: 185, ltv: 1750, conversion_rate: 22, churn_rate: 4 },
  { month: 'Jun', mrr: 9800, cac: 175, ltv: 1900, conversion_rate: 24, churn_rate: 3.5 },
];

export const churnProfiles: ChurnProfile[] = [
  {
    id: 'C001',
    name: 'Institut National Formation',
    profile_type: 'Guest',
    signals: ['G1', 'G2'],
    risk_level: 'medium',
    days_since_signal: 5,
    recovered: false,
  },
  {
    id: 'C002',
    name: 'FormaPro Institute',
    profile_type: 'Partenaire',
    signals: ['P1', 'P3'],
    risk_level: 'high',
    days_since_signal: 8,
    last_action: 'Relance chatbot envoyée',
    recovered: false,
  },
  {
    id: 'C003',
    name: 'SkillBridge Academy',
    profile_type: 'Partenaire',
    signals: ['P2'],
    risk_level: 'medium',
    days_since_signal: 3,
    recovered: false,
  },
  {
    id: 'C004',
    name: 'OldTech Industries',
    profile_type: 'Partenaire Fiable',
    signals: ['F1', 'F3'],
    risk_level: 'critical',
    days_since_signal: 14,
    last_action: 'Alerte admin envoyée',
    recovered: false,
  },
  {
    id: 'C005',
    name: 'GreenStart Corp',
    profile_type: 'Guest',
    signals: ['G3'],
    risk_level: 'high',
    days_since_signal: 6,
    recovered: false,
  },
  {
    id: 'C006',
    name: 'EduNext Platform',
    profile_type: 'Partenaire',
    signals: ['P4'],
    risk_level: 'low',
    days_since_signal: 2,
    recovered: true,
  },
];
