import React from 'react';
import { AIOffer } from '../lib/types';

interface PackageManagementProps {
  packages?: AIOffer[];
}

export const PackageManagement = ({ packages = [] }: PackageManagementProps) => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">AI Generated Offers</h1>
        <p className="text-slate-500 text-sm">Review and manage personalized commercial offers generated by the AI engine.</p>
      </div>
      {packages.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-slate-500">No packages available</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {packages.map((pkg) => (
            <div key={pkg.id} className="bg-white rounded-lg border border-slate-200 p-6">
              <h3 className="text-lg font-bold">{pkg.title || 'Offer'}</h3>
              <p className="text-sm text-slate-500 mt-2">{pkg.description || 'Generated offer'}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
