type RawData = Record<string, unknown>;

export type NormalizedRecommendedPack = {
  pack_code: string;
  pack_name: string;
  nb_rooms: number;
  services: string[];
  reason: string;
};

export type NormalizedRecommendResponse = {
  offer_id: string | null;
  updated_at: string | null;
  tier: string;
  score: number;
  offer: RawData;
  guest_id: string;
  recommended_pack: NormalizedRecommendedPack | null;
};

const isRecord = (value: unknown): value is RawData =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const toNumber = (value: unknown, fallback = 0) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const parseRecommendedPack = (value: unknown): NormalizedRecommendedPack | null => {
  if (!isRecord(value)) return null;

  const packCode = String(value.pack_code ?? "").trim();
  const packName = String(value.pack_name ?? "").trim();
  const nbRooms = toNumber(value.nb_rooms, 0);
  const services = Array.isArray(value.services)
    ? value.services.map((item) => String(item)).filter(Boolean)
    : [];
  const reason = String(value.reason ?? "").trim();

  if (!packCode && !packName && !services.length && !reason) {
    return null;
  }

  return {
    pack_code: packCode,
    pack_name: packName || packCode || "Recommended Pack",
    nb_rooms: nbRooms,
    services,
    reason: reason || "Recommendation generated by AI.",
  };
};

const inferPackFromOfferPayload = (offer: RawData): NormalizedRecommendedPack | null => {
  const packCode = String(offer.recommended_pack_code ?? offer.pack_id ?? "").trim();
  const reason = String(offer.reason ?? "").trim();
  if (!packCode && !reason) return null;

  return {
    pack_code: packCode,
    pack_name: packCode || "Recommended Pack",
    nb_rooms: 0,
    services: [],
    reason: reason || "Recommendation generated by AI.",
  };
};

export const normalizeRecommendResponse = (input: unknown): NormalizedRecommendResponse => {
  const data = isRecord(input) ? input : {};

  const offer = isRecord(data.offer) ? data.offer : {};
  const recommendedPack =
    parseRecommendedPack(data.recommended_pack) ||
    inferPackFromOfferPayload(offer);

  return {
    offer_id: typeof data.offer_id === "string" && data.offer_id.trim() ? data.offer_id : null,
    updated_at: typeof data.updated_at === "string" && data.updated_at.trim() ? data.updated_at : null,
    tier: String(data.tier ?? "Unknown").trim() || "Unknown",
    score: toNumber(data.score, toNumber(data.engagement_score, 0)),
    offer,
    guest_id: String(data.guest_id ?? "").trim(),
    recommended_pack: recommendedPack,
  };
};
