import React from 'react';
import { AIOffer, GuestWithOffer } from '../lib/types';
import { Edit3, Activity } from 'lucide-react';
import { cn } from '../lib/utils';
import { MOCK_GUESTS } from '../lib/mock-data';

interface PackageManagementProps {
  packages?: AIOffer[];
}

export const PackageManagement = ({ packages }: PackageManagementProps) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">AI Generated Offers</h1>
          <p className="text-slate-500 text-sm">Review and manage personalized commercial offers generated by the AI engine.</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors shadow-sm shadow-indigo-200">
          <Activity size={18} />
          Regenerate All Offers
        </button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {MOCK_GUESTS.map((guest) => (
          <div key={guest.id} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
            <div className="p-6 border-b border-slate-100 bg-slate-50/50">
              <div className="flex items-center justify-between mb-2">
                <span className="px-2 py-0.5 bg-white border border-slate-200 rounded text-[10px] font-bold text-slate-500 uppercase">
                  {guest.generatedOffer.status}
                </span>
                <div className="flex gap-1">
                  <button className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-white rounded-md transition-all">
                    <Edit3 size={14} />
                  </button>
                </div>
              </div>
              <h3 className="text-xl font-bold text-slate-900">{guest.generatedOffer.title}</h3>
              <p className="text-xs text-slate-500 mt-1">For: {guest.fullName} ({guest.company})</p>
            </div>

            <div className="p-6 flex-1 space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm text-slate-500">Sessions</span>
                <span className="text-sm font-bold text-slate-900">{guest.generatedOffer.sessionsIncluded}</span>
              </div>

              <div>
                <p className="text-xs font-bold text-slate-400 uppercase mb-2">Included Rooms</p>
                <div className="flex flex-wrap gap-2">
                  {guest.generatedOffer.roomsIncluded.map((room, idx) => (
                    <span key={idx} className="px-2 py-1 bg-indigo-50 text-indigo-600 rounded text-[10px] font-medium">
                      {room}
                    </span>
                  ))}
                </div>
              </div>
              <div className="p-3 bg-indigo-50 rounded-lg border border-indigo-100">
                <p className="text-[10px] font-bold text-indigo-400 uppercase mb-1">AI Reason</p>
                <p className="text-xs text-indigo-700 italic">"{guest.generatedOffer.reason}"</p>
              </div>
            </div>

            <div className="p-6 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Confidence</p>
                <p className="text-lg font-black text-slate-900">{guest.generatedOffer.confidenceScore}%</p>
              </div>
              <button className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold text-slate-700 hover:bg-slate-50 transition-colors">
                Review Offer
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
