import React from 'react';
import { AIOffer } from '../lib/types';
import { RefreshCw } from 'lucide-react';
import { MOCK_GUESTS } from '../lib/mock-data';
import { getOfferStatusBadgeClasses, getOfferStatusLabel } from '../lib/offer-status';

interface PackageManagementProps {
  packages?: AIOffer[];
}

const canRegenerate = (status: string) =>
  status === 'pending' ||
  status === 'approved' ||
  status === 'rejected' ||
  status === 'READY' ||
  status === 'DRAFT' ||
  status === 'PENDING' ||
  status === 'Offre Générée' ||
  status === 'Offre Supprimée' ||
  status === 'Offre Refusée';

export const PackageManagement = ({ packages }: PackageManagementProps) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">AI Generated Offers</h1>
          <p className="text-slate-500 text-sm">Review and manage personalized commercial offers generated by the AI engine.</p>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {MOCK_GUESTS.map((guest) => (
          <div key={guest.id} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
            <div className="p-6 border-b border-slate-100 bg-slate-50/50">
              <div className="flex items-center justify-between mb-2">
                <span className={`px-2 py-0.5 rounded text-[10px] leading-[13px] font-bold border ${getOfferStatusBadgeClasses(guest.generatedOffer.status)}`}>
                  {getOfferStatusLabel(guest.generatedOffer.status)}
                </span>
              </div>
              <h3 className="text-xl font-bold text-slate-900">{guest.generatedOffer.title}</h3>
              <p className="text-xs text-slate-500 mt-1">For: {guest.fullName} ({guest.company})</p>
            </div>

            <div className="p-6 flex-1 space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm text-slate-500">Sessions</span>
                <span className="text-sm font-bold text-slate-900">{guest.generatedOffer.sessionsIncluded}</span>
              </div>

              <div>
                <p className="text-xs font-bold text-slate-400 uppercase mb-2">Included Rooms</p>
                <div className="flex flex-wrap gap-2">
                  {guest.generatedOffer.roomsIncluded.map((room, idx) => (
                    <span key={idx} className="px-2 py-1 bg-red-50 text-red-700 rounded text-[10px] font-medium">
                      {room}
                    </span>
                  ))}
                </div>
              </div>
              <div className="p-3 bg-red-50 rounded-lg border border-red-100">
                <p className="text-[10px] font-bold text-red-500 uppercase mb-1">AI Reason</p>
                <p className="text-xs text-red-800 italic">"{guest.generatedOffer.reason}"</p>
              </div>
            </div>

            <div className="p-6 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Confidence</p>
                <p className="text-lg font-black text-slate-900">{guest.generatedOffer.confidenceScore}%</p>
              </div>
              <div className="flex items-center gap-2">
                {canRegenerate(String(guest.generatedOffer.status)) && (
                  <button className="flex items-center gap-1.5 px-2.5 py-1 bg-indigo-50 text-indigo-600 border border-indigo-200 rounded-lg text-[10px] font-bold hover:bg-indigo-100 transition-colors">
                    <RefreshCw size={12} />
                    Regenerate
                  </button>
                )}
                <button className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold text-slate-700 hover:bg-slate-50 transition-colors">
                  Review Offer
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
